<template>
  <div class="p-6 space-y-4 h-full flex flex-col">
    <!-- Header -->
    <header class="flex-none px-6 py-4 flex items-center justify-between border-b border-[var(--color-border)]">
      <div>
        <h1 class="text-xl font-bold">Projects</h1>
        <p class="text-xs text-[var(--color-muted)] mt-1 flex items-center gap-1">
          Managing {{ projects.length }} web orchestration stacks 
          <span v-if="routerRunning" class="flex items-center gap-1 text-[var(--color-success)] ml-2">
             <span class="w-1.5 h-1.5 bg-[var(--color-success)] rounded-full animate-pulse"></span>
             Router Active
          </span>
          <span v-else class="flex items-center gap-1 text-[var(--color-danger)] ml-2 bg-[var(--color-danger)]/10 px-1.5 py-0.5 rounded cursor-pointer" @click="$emit('navigate', 'nginx')">
             Router Offline
          </span>
        </p>
      </div>
      <button @click="openWizard()" class="cursor-pointer flex items-center gap-1.5 bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white text-sm font-medium px-4 py-2 rounded-xl transition shadow-lg shadow-[var(--color-accent)]/20">
        <AppIcon name="plus" :size="16" class="pointer-events-none" /> New Project
      </button>
    </header>

    <!-- Active Projects List -->
    <div class="flex-1 overflow-y-auto">
      <div v-if="projects.length === 0" class="flex flex-col items-center justify-center h-48 text-[var(--color-muted)]">
        <AppIcon name="template" :size="48" class="mb-4 opacity-50" />
        <p>No projects configured yet.</p>
        <button @click="openWizard" class="cursor-pointer mt-4 text-[var(--color-accent)] hover:underline text-sm">Create your first database/web stack</button>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <ProjectCard
          v-for="proj in projects" :key="proj.id"
          :project="proj"
          :status="projectStatuses[proj.id] || 'stopped'"
          @edit="editProject(proj)"
          @redeploy="redeployProject(proj)"
          @inspect="openInspect(proj)"
          @launch="launchProject(proj)"
          @stop="stopProject(proj)"
        />
      </div>
    </div>

    <!-- Project Wizard Modal -->
    <ProjectWizardModal
      :show="showWizard"
      :is-editing="!!editingProjectId"
      :wizard="wizard"
      :php-extension-categories="phpExtensionCategories"
      :get-available-tags-for-image="getAvailableTagsForImage"
      :is-ext-incompatible="isExtIncompatible"
      @close="closeWizard"
      @save="generateAndSave"
      @browse="browseSourceCode"
      @auto-domain="autoGenerateDomain"
      @add-preset="addServicePreset"
      @toggle-expand="toggleServiceExpand"
      @remove-service="removeService"
      @open-library="openLibrary"
      @update-tag="(idx: number, tag: string) => updateImageTag(idx, tag)"
      @update:wizard="(w: any) => { wizard.name = w.name; wizard.domain = w.domain; wizard.path = w.path; }"
    />

    <!-- YAML Viewer Modal -->
    <YamlViewerModal :show="showYamlModal" :title="yamlViewTitle" :content="yamlViewContent" @close="showYamlModal = false" />
    
    <!-- Deploy Modal -->
    <DeployModal :show="showLaunchModal" :target-name="launchTargetName" :logs="launchLogs" :launching="launching" @close="closeLaunchModal" />

    <!-- Project-specific Resizable Drawer -->
    <ServiceDrawer 
      v-if="inspectedProject"
      :is-open="isDrawerOpen"
      v-model:active-tab="activeTab"
      :tabs="drawerTabs"
      icon="code"
      @close="closeInspect"
      @open="isDrawerOpen = true"
    >
      <template #header-extra v-if="inspectedProject && inspectedProject.config.services.length > 1">
        <div class="flex items-center gap-2 bg-black/20 p-1 rounded-lg border border-[var(--color-border)] ml-4">
          <button 
            v-for="(svc, idx) in inspectedProject.config.services" 
            :key="idx"
            @click="inspectedServiceIdx = idx"
            class="cursor-pointer px-3 py-1 text-[10px] font-bold uppercase tracking-wider rounded transition"
            :class="inspectedServiceIdx === idx ? 'bg-[var(--color-accent)] text-white' : 'text-[var(--color-muted)] hover:text-white'"
          >
            {{ svc.name }}
          </button>
        </div>
      </template>

      <template #logs>
        <ContainerLogs
          v-if="activeTab === 'logs' && inspectedProject"
          :container-id="getContainerId(inspectedProject, inspectedServiceIdx)"
          :name="inspectedProject.config.services[inspectedServiceIdx]?.name || inspectedProject.name"
          class="h-full"
        />
      </template>

      <template #terminal>
        <ContainerTerminal
          v-if="activeTab === 'terminal' && inspectedProject && containerRunning"
          :container-id="getContainerId(inspectedProject, inspectedServiceIdx)"
          :name="inspectedProject.config.services[inspectedServiceIdx]?.name || inspectedProject.name"
          class="h-full"
        />
        <div v-else class="h-full bg-black flex items-center justify-center text-[var(--color-muted)] font-mono text-xs">
           <div class="text-center">
              <AppIcon name="terminal" :size="48" class="mx-auto mb-4 opacity-20" />
              Container <strong>{{ inspectedProject?.config.services[inspectedServiceIdx]?.name }}</strong> must be running to open terminal.
           </div>
        </div>
      </template>

      <template #info>
        <ContainerInfo
          v-if="activeTab === 'info' && inspectedProject"
          :container-id="getContainerId(inspectedProject, inspectedServiceIdx)"
          :name="inspectedProject.config.services[inspectedServiceIdx]?.name || inspectedProject.name"
          class="h-full"
        />
      </template>

      <template #config>
        <div v-if="inspectedProject" class="h-full bg-[var(--color-surface)] flex flex-col">
          <!-- File Tabs Selector -->
          <div class="px-6 pt-4 flex gap-2 border-b border-[var(--color-border)] overflow-x-auto bg-black/10 shrink-0">
             <button 
                v-for="(content, fileName) in editingFiles" 
                :key="fileName"
                @click="activeConfigFileName = fileName"
                class="cursor-pointer px-4 py-2 text-[10px] font-bold uppercase tracking-widest border-b-2 transition"
                :class="activeConfigFileName === fileName ? 'border-[var(--color-accent)] text-white bg-white/5' : 'border-transparent text-[var(--color-muted)] hover:text-white'"
             >
                {{ fileName }}
             </button>
          </div>

          <div class="p-6 flex-1 flex flex-col min-h-0">
            <div class="flex items-center justify-between mb-4 flex-shrink-0">
              <div>
                <h4 class="text-xs font-bold text-[var(--color-accent)] uppercase tracking-widest">{{ activeConfigFileName }}</h4>
                <p class="text-[10px] text-[var(--color-muted)] mt-1 italic">Manual edits will be saved directly to the file on disk.</p>
              </div>
              
              <button 
                v-if="isConfigModified"
                @click="saveActiveConfigFile" 
                class="cursor-pointer px-4 py-1.5 bg-[var(--color-accent)] hover:bg-[var(--color-accent-hover)] text-white text-xs font-bold rounded-lg transition shadow-lg shadow-[var(--color-accent)]/20"
              >
                Save File
              </button>
              <div v-else-if="configSaved" class="text-xs text-[var(--color-success)] font-bold flex items-center gap-1">
                <AppIcon name="check" :size="12" /> Saved!
              </div>
              <div v-else class="text-[10px] text-[var(--color-muted)] font-mono">Editing Mode</div>
            </div>
            
            <div class="flex-1 min-h-0 relative flex border border-[var(--color-border)] rounded-xl overflow-hidden bg-black/40">
              <!-- Line Numbers -->
              <div ref="lineNumbersRef" class="w-10 bg-black/20 border-r border-[var(--color-border)] py-4 flex-shrink-0 text-right pr-2 select-none pointer-events-none overflow-hidden">
                <div v-for="n in (editingFiles[activeConfigFileName] || '').split('\n').length" :key="n" class="text-[11px] leading-relaxed text-[var(--color-muted)] font-mono">
                  {{ n }}
                </div>
              </div>
              
              <!-- Editor -->
              <textarea 
                ref="editorRef"
                v-model="editingFiles[activeConfigFileName]" 
                @scroll="syncScroll"
                @keydown="handleEditorKeyDown"
                spellcheck="false"
                class="flex-1 h-full bg-transparent p-4 pr-1 text-[13px] text-gray-200 font-mono focus:outline-none resize-none leading-relaxed overflow-x-auto whitespace-pre"
              ></textarea>
            </div>
          </div>
        </div>
      </template>

      <template #history>
        <div v-if="inspectedProject" class="h-full bg-[var(--color-surface)] p-6 overflow-auto">
          <div class="flex items-center justify-between mb-6">
            <h4 class="text-xs font-bold text-[var(--color-accent)] uppercase tracking-widest">Deployment Timeline</h4>
            <div class="text-[10px] text-[var(--color-muted)]">{{ (inspectedProject.deployHistory || []).length }} sessions saved</div>
          </div>

          <div v-if="!(inspectedProject.deployHistory || []).length" class="text-center py-20 opacity-30">
            <AppIcon name="refresh" :size="48" class="mx-auto mb-4" />
            <p class="text-sm">No deployment history yet.</p>
          </div>

          <div v-else class="space-y-4 pb-12">
            <div v-for="(session, idx) in [...(inspectedProject.deployHistory || [])].reverse()" :key="idx" class="border border-[var(--color-border)] rounded-xl overflow-hidden bg-black/20">
              <div class="p-3 bg-white/5 flex items-center justify-between">
                <div class="flex items-center gap-3">
                  <span :class="session.success ? 'text-green-500' : 'text-red-500'">
                    <AppIcon :name="session.success ? 'check' : 'close'" :size="14" />
                  </span>
                  <span class="text-xs font-medium text-white">{{ session.timestamp }}</span>
                </div>
                <div class="text-[10px] uppercase font-bold tracking-wider" :class="session.success ? 'text-green-500/50' : 'text-red-500/50'">
                  {{ session.success ? 'Success' : 'Failed' }}
                </div>
              </div>
              <div class="p-3">
                <pre class="text-[11px] text-gray-400 font-mono whitespace-pre-wrap max-h-[150px] overflow-y-auto leading-relaxed">{{ session.log }}</pre>
              </div>
            </div>
          </div>
        </div>
      </template>
    </ServiceDrawer>

    <!-- Delete Confirmation Modal -->
    <DeleteProjectModal :show="showDeleteModal" :project-name="projectToDelete?.name || ''" @close="showDeleteModal = false" @confirm="doDeleteProject" />

    <!-- Docker Image Library Modal -->
    <ImageLibraryModal
      :service-idx="showLibrary.serviceIdx"
      :categories="filteredLibraryCategories"
      @close="showLibrary.serviceIdx = null"
      @select="selectLibraryImage"
    />
  </div>
</template>


<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from 'vue';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';
import { open } from '@tauri-apps/plugin-dialog';
import AppIcon from '../components/AppIcon.vue';
import ServiceDrawer from '../components/ServiceDrawer.vue';
import ContainerLogs from '../components/ContainerLogs.vue';
import ContainerTerminal from '../components/ContainerTerminal.vue';
import ContainerInfo from '../components/ContainerInfo.vue';
import ProjectCard from '../components/ProjectCard.vue';
import ProjectWizardModal from '../components/modals/ProjectWizardModal.vue';
import YamlViewerModal from '../components/modals/YamlViewerModal.vue';
import DeployModal from '../components/modals/DeployModal.vue';
import DeleteProjectModal from '../components/modals/DeleteProjectModal.vue';
import ImageLibraryModal from '../components/modals/ImageLibraryModal.vue';
import { generateComposeTemplate, generateNginxConfig, getContainerId } from '../composables/useDockerGenerator';
import type { Project, DeploySession } from '../composables/useDockerGenerator';
import { useCodeEditor } from '../composables/useCodeEditor';
import { useProjectStore } from '../composables/useProjectStore';
import { useProjectWizard } from '../composables/useProjectWizard';

// ── Composables ──────────────────────────────────────────────
const store = useProjectStore();
const {
  projects, projectStatuses, routerRunning,
  loadProjects, saveProjectsLocal, checkRouterStatus,
  refreshProjectStatuses, saveProjectFile, saveAllProjectFiles,
  deleteProject,
} = store;

const wiz = useProjectWizard();
const {
  showWizard, editingProjectId, wizard,
  phpExtensionCategories, showLibrary, filteredLibraryCategories,
  openLibrary, selectLibraryImage, getAvailableTagsForImage,
  updateImageTag, isExtIncompatible,
  addServicePreset, removeService, toggleServiceExpand,
  openWizard, closeWizard, autoGenerateDomain,
} = wiz;

// ── YAML Viewer ──────────────────────────────────────────────
const showYamlModal = ref(false);
const yamlViewTitle = ref('');
const yamlViewContent = ref('');

// ── Deploy Modal ─────────────────────────────────────────────
const showLaunchModal = ref(false);
const launchTargetName = ref('');
const launchLogs = ref('');
const launching = ref(false);

// ── Delete Modal ─────────────────────────────────────────────
const showDeleteModal = ref(false);
const projectToDelete = ref<Project | null>(null);

// ── Drawer / Inspector ───────────────────────────────────────
const isDrawerOpen = ref(false);
const inspectedProject = ref<Project | null>(null);
const activeTab = ref('logs');
const inspectedServiceIdx = ref(0);
const editingFiles = ref<Record<string, string>>({});
const activeConfigFileName = ref('docker-compose.yml');
const configSaved = ref(false);
const containerRunning = ref(false);

const isConfigModified = computed(() => {
  if (!inspectedProject.value) return false;
  const original = activeConfigFileName.value === 'docker-compose.yml'
    ? inspectedProject.value.yaml
    : '';
  return editingFiles.value[activeConfigFileName.value] !== original;
});

const { lineNumbersRef, editorRef, syncScroll, handleKeyDown: editorHandleKeyDown } = useCodeEditor(() => saveActiveConfigFile());

function handleEditorKeyDown(e: KeyboardEvent) {
  editorHandleKeyDown(e, {
    get value() { return editingFiles.value[activeConfigFileName.value]; },
    set value(v: string) { editingFiles.value[activeConfigFileName.value] = v; }
  });
}

const drawerTabs = [
  { id: 'logs', label: 'Logs' },
  { id: 'terminal', label: 'Terminal' },
  { id: 'config', label: 'Config (YAML)' },
  { id: 'history', label: 'Deploy History' },
  { id: 'info', label: 'Inspect' }
];

let unlistenCompose: (() => void) | undefined;

// ── Actions ──────────────────────────────────────────────────

function editProject(proj: Project) {
  editingProjectId.value = proj.id;
  wizard.value = {
    name: proj.name,
    domain: proj.domain,
    path: proj.path,
    services: JSON.parse(JSON.stringify(proj.config.services)).map((s: any) => ({ ...s, expanded: false }))
  };
  showWizard.value = true;
}

async function browseSourceCode() {
  const selected = await open({ directory: true, multiple: false, title: 'Select Source Code Directory' });
  if (selected && typeof selected === 'string') {
    wizard.value.path = selected;
  }
}

async function openInspect(proj: Project) {
  inspectedProject.value = proj;
  inspectedServiceIdx.value = 0;
  activeConfigFileName.value = 'docker-compose.yml';
  editingFiles.value = { 'docker-compose.yml': proj.yaml };
  configSaved.value = false;
  isDrawerOpen.value = true;
  activeTab.value = 'logs';
  containerRunning.value = false;

  const safeName = proj.name.toLowerCase().replace(/[^a-z0-9]/g, '-');

  try {
    const routerConf = await invoke<string>('read_router_config', { projectName: safeName });
    editingFiles.value[safeName + '.conf'] = routerConf;
  } catch {
    if (proj.config.services.some(s => s.isPublic)) {
      editingFiles.value[safeName + '.conf'] = generateNginxConfig(proj);
    }
  }

  for (const svc of proj.config.services) {
    if (svc.type === 'php' || svc.type === 'laravel') {
      try {
        const df = await invoke<string>('read_project_file', { projectName: safeName, fileName: `Dockerfile.${svc.name}` });
        editingFiles.value[`Dockerfile.${svc.name}`] = df;
      } catch {}
      try {
        const ini = await invoke<string>('read_project_file', { projectName: safeName, fileName: `php-custom-${svc.name}.ini` });
        editingFiles.value[`php-custom-${svc.name}.ini`] = ini;
      } catch {}
    }
  }

  try {
    const info = await invoke<any>('inspect_container', { id: getContainerId(proj, 0) });
    containerRunning.value = info.State?.Status === 'running';
  } catch {
    containerRunning.value = false;
  }
}

async function saveActiveConfigFile() {
  if (!inspectedProject.value) return;
  const proj = inspectedProject.value;
  const fileName = activeConfigFileName.value;
  const content = editingFiles.value[fileName];
  const safeName = proj.name.toLowerCase().replace(/[^a-z0-9]/g, '-');

  if (fileName === 'docker-compose.yml') {
    proj.yaml = content;
    saveProjectsLocal();
    await saveProjectFile(safeName, fileName, content);
  } else if (fileName.endsWith('.conf')) {
    proj.routerConfig = content;
    saveProjectsLocal();
    await invoke('save_router_config', { projectName: safeName, content });
    await invoke('reload_nginx_proxy');
  } else {
    await saveProjectFile(safeName, fileName, content);
  }

  configSaved.value = true;
  setTimeout(() => { configSaved.value = false; }, 2000);
}

function closeInspect() {
  isDrawerOpen.value = false;
  inspectedProject.value = null;
}

// ── Project Lifecycle ────────────────────────────────────────

async function startProject(proj: Project) {
  try { await invoke('start_container', { id: getContainerId(proj) }); } catch (e) { console.error('Start failed:', e); }
  await refreshProjectStatuses(getContainerId);
}

async function stopProject(proj: Project) {
  try { await invoke('stop_container', { id: getContainerId(proj) }); } catch (e) { console.error('Stop failed:', e); }
  await refreshProjectStatuses(getContainerId);
}

async function redeployProject(proj: Project) {
  showLaunchModal.value = true;
  launchTargetName.value = proj.name;
  launchLogs.value = 'Redeploying project...\n';
  launching.value = true;

  try {
    launchLogs.value += 'Stopping container...\n';
    try { await invoke('stop_container', { id: getContainerId(proj) }); } catch (_) {}
    launchLogs.value += 'Removing container...\n';
    try { await invoke('remove_container', { id: getContainerId(proj) }); } catch (_) {}
    launchLogs.value += 'Refreshing project files on disk...\n';
    saveAllProjectFiles(proj);
    launchLogs.value += 'Re-deploying with current config...\n';
    await launchProject(proj);
    return;
  } catch (e) {
    launchLogs.value += `Error: ${e}\n`;
  } finally {
    launching.value = false;
  }
}

function generateAndSave() {
  const w = wizard.value;
  const yaml = generateComposeTemplate(w);

  if (editingProjectId.value) {
    const idx = projects.value.findIndex(p => p.id === editingProjectId.value);
    if (idx !== -1) {
      projects.value[idx] = {
        ...projects.value[idx],
        name: w.name, domain: w.domain, path: w.path,
        config: { services: w.services.map(s => ({ ...s, expanded: false })) },
        yaml
      };
    }
  } else {
    const newProj: Project = {
      id: Date.now().toString(),
      name: w.name, domain: w.domain, path: w.path,
      config: { services: w.services.map(s => ({ ...s, expanded: false })) },
      yaml
    };
    projects.value.push(newProj);
  }

  saveProjectsLocal();
  const savedProj = editingProjectId.value
    ? projects.value.find(p => p.id === editingProjectId.value)
    : projects.value[projects.value.length - 1];
  if (savedProj) saveAllProjectFiles(savedProj);
  closeWizard();
}

async function launchProject(proj: Project) {
  showLaunchModal.value = true;
  launchTargetName.value = proj.name;
  launchLogs.value = 'Preparing configuration for Engine...\n';
  launching.value = true;

  try {
    const safeName = proj.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
    launchLogs.value += `Executing engine rollout via Tauri Backend...\n`;
    const result = await invoke<string>('launch_compose', {
      yaml: proj.yaml,
      projectName: `wdp-${safeName}`,
      workingDir: `~/.wDocker/projects/${safeName}`
    });
    launchLogs.value += `\nDeployment Triggered: ${result}\nIf Nginx Proxy is active, domain http://${proj.domain} should be routable soon.`;

    const session: DeploySession = { timestamp: new Date().toLocaleString(), log: launchLogs.value, success: true };
    if (!proj.deployHistory) proj.deployHistory = [];
    proj.deployHistory.push(session);
    if (proj.deployHistory.length > 10) proj.deployHistory.shift();
    saveProjectsLocal();
  } catch (e) {
    launchLogs.value += `\nFailed to start project: ${e}`;
    const session: DeploySession = { timestamp: new Date().toLocaleString(), log: launchLogs.value, success: false };
    if (!proj.deployHistory) proj.deployHistory = [];
    proj.deployHistory.push(session);
    if (proj.deployHistory.length > 10) proj.deployHistory.shift();
    saveProjectsLocal();
  } finally {
    launching.value = false;
    await refreshProjectStatuses(getContainerId);
  }
}

function closeLaunchModal() {
  showLaunchModal.value = false;
  launchLogs.value = '';
}

function confirmDeleteProject(proj: Project) {
  projectToDelete.value = proj;
  showDeleteModal.value = true;
}

function doDeleteProject() {
  if (projectToDelete.value) {
    deleteProject(projectToDelete.value);
    showDeleteModal.value = false;
    projectToDelete.value = null;
  }
}

async function updateInspectedServiceStatus() {
  if (!inspectedProject.value) return;
  try {
    const info = await invoke<any>('inspect_container', { id: getContainerId(inspectedProject.value, inspectedServiceIdx.value) });
    containerRunning.value = info.State?.Status === 'running';
  } catch {
    containerRunning.value = false;
  }
}

watch(inspectedServiceIdx, () => updateInspectedServiceStatus());

onMounted(async () => {
  loadProjects();
  checkRouterStatus();
  const listenFn = await listen<string>('compose-progress', (event) => {
    if (showLaunchModal.value) {
      launchLogs.value += event.payload + '\n';
      const pre = document.querySelector('.bg-\\[\\#0f111a\\]');
      if (pre) pre.scrollTop = pre.scrollHeight;
    }
  });
  unlistenCompose = listenFn;
  await refreshProjectStatuses(getContainerId);
});

onUnmounted(() => {
  if (unlistenCompose) unlistenCompose();
});
</script>

